export const proyectos = [
    {
        'nombre': 'Juego del ahorcado',
        'descripcion': 'Pequeño juego del ahorcado en donde el usuario debe adivinar una serie de letras de una palabra antes de que se terminen sus oportunidades.',
        'img': 'ahorcado.png',
        'repositorio': 'https://github.com/JustLearningMX/juego-ahorcado',
        'demostracion': 'https://justlearningmx.github.io/juego-ahorcado/',
        'stack': ['HTML', 'CSS', 'JS'],
        'proyectos': true,
        'alt': 'Juego del ahorcado',
    },
    {
        'nombre': 'Purificadora',
        'descripcion': 'Aplicación web basica que permite llevar el control de compras de botellones por agua por cliente para otorgar un llenado gratis. Actualmente en construcción.',
        'img': 'purificadora.png',
        'repositorio': 'https://github.com/JustLearningMX/purificadora',
        'demostracion': 'https://purificadora-rio-jordan.herokuapp.com/',
        'stack': ['HTML', 'CSS', 'JS'],
        'proyectos': true,
        'alt': 'Purificadora de agua',
    },
    {
        'nombre': 'Purificadora React',
        'descripcion': 'Aplicación web con React que permite llevar el control de compras de botellones por agua por cliente para otorgar un llenado gratis. Actualmente en construcción.',
        'img': 'purificadoraReact.png',
        'repositorio': 'https://github.com/JustLearningMX/purificadorariojordan',
        'demostracion': 'https://purificadorariojordan.vercel.app/',
        'stack': ['HTML', 'CSS', 'JS', 'React', 'Redux', 'React Router'],
        'proyectos': true,
        'alt': 'Purificadora de agua con React',
    },
    {
        'nombre': 'Purificadora-api',
        'descripcion': 'API Rest de la aplicación purificadora. Gestiona la información de la BD mediante endpoints que se consumen desde el frontend.',
        'img': 'purificadora-api.png',
        'repositorio': 'https://github.com/JustLearningMX/purificadora_api',
        'demostracion': 'https://purificadora-rio-jordan-api.herokuapp.com/v1/api-docs/',
        'demostracion2': 'https://purificadora-api-hir-dev.apps.sandbox-m3.1530.p1.openshiftapps.com/v1/api-docs/',
        'stack': ['MongoDB', 'ExpressJS', 'NodeJS', 'JS'],
        'proyectos': true,
        'alt': 'API Rest de la Purificadora de agua',
    },
    {
        'nombre': 'Schoolwebapp',
        'descripcion': 'Aplicación web que permite a estudiantes y maestros registrarse del colegio ficticio Águila. Se generar un CRUD básico con PHP.',
        'img': 'colegio.png',
        'repositorio': 'https://github.com/JustLearningMX/schoolwebapp_pw2u2',
        'demostracion': 'https://safe-stream-39211.herokuapp.com/',
        'stack': ['HTML', 'CSS', 'JS', 'PHP', 'MySQL'],
        'proyectos': true,
        'alt': 'Aplicación ficticia de un colegio',
    },
    {
        'nombre': 'flipbook',
        'descripcion': 'Aplicación web frontend que permite comentar libros. Utiliza React para dibujar las vistas y se hace uso de HTML, CSS y JS.',
        'img': 'flipbook.png',
        'repositorio': 'https://github.com/JustLearningMX/libreria-1',
        'demostracion': 'https://libreria-bedu.herokuapp.com/',
        'stack': ['HTML', 'CSS', 'JS', 'React'],
        'proyectos': true,
        'alt': 'Aplicación para comentar libros',
    },
    {
        'nombre': 'libreriapi',
        'descripcion': 'API Rest de la aplicación flipbook. Gestiona la información de la BD mediante endpoints que se consumen desde el frontend. ',
        'img': 'libreriapi.png',
        'repositorio': 'https://github.com/JustLearningMX/LibreriApi',
        'demostracion': 'https://libreriapi.herokuapp.com/v1/api-docs/',
        'demostracion2': 'https://libreri-api-hir-dev.apps.sandbox-m3.1530.p1.openshiftapps.com/v1/api-docs/',
        'stack': ['MongoDB', 'ExpressJS', 'NodeJS', 'JS'],
        'proyectos': true,
        'alt': 'API Rest de la aplicación para comentar libros',
    },
];