export const proyectos = [
    {
        'nombre': 'Juego del ahorcado',
        'descripcion': 'Pequeño juego del ahorcado en donde el usuario debe adivinar una serie de letras de una palabra antes de que se terminen sus oportunidades.',
        'img': '../source/assets/projects/ahorcado.png',
        'repositorio': 'https://github.com/JustLearningMX/juego-ahorcado',
        'demostracion': 'https://justlearningmx.github.io/juego-ahorcado/',
        'stack': ['HTML', 'CSS', 'JS'],
        'proyectos': true,
    },
    {
        'nombre': 'Purificadora',
        'descripcion': 'Aplicación web que permite llevar el control de compras de botellones por agua por cliente para otorgar un llenado gratis. Actualmente en construcción.',
        'img': '../source/assets/projects/purificadora.png',
        'repositorio': 'https://github.com/JustLearningMX/purificadora',
        'demostracion': 'https://purificadora-rio-jordan.herokuapp.com/',
        'stack': ['HTML', 'CSS', 'JS'],
        'proyectos': true,
    },
    {
        'nombre': 'Purificadora-api',
        'descripcion': 'API Rest de la aplicación purificadora. Gestiona la información de la BD mediante endpoints que se consumen desde el frontend.',
        'img': '../source/assets/projects/purificadora-api.png',
        'repositorio': 'https://github.com/JustLearningMX/purificadora_api',
        'demostracion': 'https://purificadora-rio-jordan-api.herokuapp.com/v1/api-docs/',
        'stack': ['MongoDB', 'ExpressJS', 'NodeJS', 'JS'],
        'proyectos': true,
    },
    {
        'nombre': 'Schoolwebapp',
        'descripcion': 'Aplicación web que permite a estudiantes y maestros registrarse del colegio ficticio Águila. Se generar un CRUD básico con PHP.',
        'img': '../source/assets/projects/colegio.png',
        'repositorio': 'https://github.com/JustLearningMX/schoolwebapp_pw2u2',
        'demostracion': 'https://safe-stream-39211.herokuapp.com/',
        'stack': ['HTML', 'CSS', 'JS', 'PHP', 'MySQL'],
        'proyectos': true,
    },
    {
        'nombre': 'flipbook',
        'descripcion': 'Aplicación web frontend que permite comentar libros. Utiliza React para dibujar las vistas y se hace uso de HTML, CSS y JS.',
        'img': '../source/assets/projects/flipbook.png',
        'repositorio': 'https://github.com/JustLearningMX/libreria-1',
        'demostracion': 'https://libreria-bedu.herokuapp.com/',
        'stack': ['HTML', 'CSS', 'JS', 'React'],
        'proyectos': true,
    },
    {
        'nombre': 'libreriapi',
        'descripcion': 'API Rest de la aplicación flipbook. Gestiona la información de la BD mediante endpoints que se consumen desde el frontend.',
        'img': '../source/assets/projects/libreriapi.png',
        'repositorio': 'https://github.com/JustLearningMX/LibreriApi',
        'demostracion': 'https://libreriapi.herokuapp.com/v1/api-docs/',
        'stack': ['MongoDB', 'ExpressJS', 'NodeJS', 'JS'],
        'proyectos': true,
    },
];